include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_redundant_argument_values: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
